### ISSUE TITLE
create a ppa for conky-manager

### ISSUE THREAD

**Issue by freddii** [zcot/conky-manager2#20]
It would be useful to have a ppa for conky manger at  https://launchpad.net .
So people can install it without having to compile it.

Are there any plans to bring conky-manager to launchpad?

**Comment by afelinczak** [comment]
Hey,
I have conky-manager on my personal PPA that was created for ClipIt.
https://launchpad.net/~afelinczak/+archive/ubuntu/ppa?field.series_filter=focal
It is not official though as I'm not contributor to conky-manager.
It should be up to date with master branch.

**Comment by freddii** [comment]
maybe that ppa can be added to README.md

**Comment by afelinczak** [comment]
Updated ppa with the latest changes - build with meson

**Comment by zcot** [comment]
The ppa is stale(abandoned?), do not use it.

Use the ppa set by original designer teejee Tony George instead, updated daily: https://github.com/zcot/conky-manager2/commit/4dbad46373a07552687ed924777bb5477276ee02

See README: https://github.com/zcot/conky-manager2#installation
