### ISSUE TITLE
conky-manager2 fails to create a preview image with lua-based configs

### ISSUE THREAD

**Issue by freddii** [zcot/conky-manager2#23]
OS: Debian GNU/Linux bullseye/sid x86_64
DE: Xfce 4.16 
WM: Xfwm4 

conky 1.11.6 compiled 2020-08-17 for Linux x86_64

when click on "Generate preview images" conky-manager2 does not create preview images.

**Comment by zcot** [comment]
This feature will fail when using 1.10 lua-based format configs.

**Comment by freddii** [comment]
works with latest add-1.10-support-branch

**Comment by zcot** [comment]
For some unknown reason, it will also _sometimes_ fail when using the old format config. But you can try it again and then it will probably succeed.
