### ISSUE TITLE
xsession-errors not showing which window creates the error

### ISSUE THREAD

**Issue by Lowrida** [zcot/conky-manager2#33]
When there pops an error in xsession-errors it only says "conky: blabla warning error danger", but not which windows/script creates it?
I have about 45 scripts running and it is a pain in the ass to find which script creates the error!
Tried 
```own_window_class =``` with unique name
```own_window_type =``` with unique name
```own_window_name =``` with unique name
But none of them adds the name of the script to the error message.

Is this actually possible? To add scriptname in the message? If not, maybe an idea?

**Comment by zcot** [comment]
I do not know if it will help or not, because you only mention "conky: blabla warning error danger", but using the manager, you can select a config then start it with the "Start in terminal" option and this will show the conky output info and issues and output related to the config.

But if there is a conky-manager2 error then it will show as "conky-manager2: blabla warning error danger".

The conky project is there: https://github.com/brndnmtthws/conky

**Comment by Lowrida** [comment]
It doesn't matter, any warning of conky only says "conky: warning message". But you are right, i'm complaining on the wrong hub haha.. forgot that this was the manager.

But i have to thank you for pointing me to the first icon, the start in terminal option! I never ever clicked on that one for all these years and had no clue that it was for that! So i tested it on 1 of 45 scripts and it immediately burped out an error message that i was seeing in the log for a long time and didn't know from which one it came! So after all i'm glad i posted here anyway! ;)

**Comment by zcot** [comment]
Ha, that's great luck!

Also, to mention, the "Start in terminal" option has only been there for 8 months or so. Before that it was some other option that neither of us have clicked on for years(arrows, to move the selector in the config list). :smiley: https://github.com/zcot/conky-manager2/commit/e76c7502074189ebc5663ae362194ca10da92bf1

**Comment by Lowrida** [comment]
Now you mention it... indeed, i do remember that! And i didn't use it because it was pointless! Using arrow down and space was much faster then clicking these icons! Maybe that's why i never noticed it was changed by a terminal icon? ;)
But certainly very useful now!
