### ISSUE TITLE
conky must be installed, or conky-manager2 shows error

### ISSUE THREAD

**Issue by MatBenA** [zcot/conky-manager2#36]
When i launch it, it gives me this error message, what can i do?
![image](https://user-images.githubusercontent.com/90014758/186554776-1b07767c-02d5-411f-ae2d-7359af3df31b.png)

**Comment by MatBenA** [comment]
I managed to install the missing package with Synaptic

**Comment by zcot** [comment]
Good job.

Yes, conky will be required, if you want to use the manager to manage the configs.

With different distros, versions, and different ways for conky itself to be packaged, the conky-manager2 program will not attempt to install conky for you. But it will continue to be a requirement for conky-manager2 to be of any use.
