### ISSUE TITLE
Cannot run after compiling from source.

### ISSUE THREAD

**Issue by Spyder-0** [zcot/conky-manager2#37]
**Here is the error after I try running it on Linux Mint 21:**
```
[17:16:45] Error: Commands listed below are not available:

 * conky

Please install required packages and try running it again
```

**Comment by zcot** [comment]
#36 will have important info.

conky-manager2 will not attempt to install conky for you, there is too many variations and optional differences between distros and versions, but conky-manager2 will help to manage configs for you, if you are using conky.

**Comment by Spyder-0** [comment]
Ok, so I need to install Conky myself then? `sudo apt install conky`. Is that how I do it?

**Comment by zcot** [comment]
At least with Ubuntu, `conky` is a virtual package and will need to refer to either `conky-cli`, `conky-std`, or `conky-all`. I would typically use, for example, on Mint, `apt install conky-all`, this way you get good participation with other useful dependencies.

You will have to do what is the most useful according to your distro.

**Comment by Spyder-0** [comment]
Ok thanks!
