### ISSUE TITLE
[11:19:24] Alpine(ARM*) Error: Commands listed below are not available:   * import

### ISSUE THREAD

**Issue by mchnjt** [zcot/conky-manager2#39]
- I'm compiling this on Alpine Linux (ARM*)
![Screenshot_2022-12-11_11-21-47](https://user-images.githubusercontent.com/83752061/206900640-069dfaee-aa5c-4fce-82cf-442b7f028bab.png)

While comparing to the Ubuntu dependencies to build this package, i successfully compiled conky-manager2 (with some errors, they're not important-ish because the program works). Commonly pre-installed runtime dependency (`7za`, `rsync`) can be just installed with `apk add p7zip rsync`. Still, i don't have an idea which package provides the `import` command

**Comment by mchnjt** [comment]
`apk add imagemagick` solved the problem.

**Comment by zcot** [comment]
Yes, the build dependency and runtime dependency are suggested: https://github.com/zcot/conky-manager2/blob/add-1.10-support/HOWTOBUILD.md#additional-required-packages-to-build

So on a different system we can use that info to try to satisfy dependency.

Good job!
